# Generated by Django 3.0.6 on 2020-05-17 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='app_answer_questio_d80d42_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='app_rating_object__57496a_idx',
        ),
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['content_type', 'object_id'], name='app_rating_content_bd7050_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['author'], name='app_rating_author__149c4f_idx'),
        ),
    ]
